services:
  backend:
    image: matickuhar/smartsearch-backend:5.0
    platform: linux/amd64
    container_name: smartsearch-backend
    volumes:
      - ./output:/app/output
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
      - mongo-seed
    restart: always

  mongo:
    image: mongo:8.0
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    restart: always

  mongo-seed:
    image: mongo:8.0
    depends_on:
      - mongo
    volumes:
      - ./mongo-init:/mongo-init
    entrypoint: [ "sh", "/mongo-init/init.sh" ]
    restart: "no"

volumes:
  mongo_data: